# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7449ddf3e8b8cc1170d1ebf60afc93799a78bee11bf2e232d063fb22a71f668d13e41ce9f3e743b04aea243b863174d1b64bca4c12bc287ca9041e88acd0625

test:
  secret_key_base: 6d01274b2aaa3baa92b0110c40023b07e4cb62c42ff787231fca4e15466bda28c7d0b57ed43ff04bdd016a9761d362569cf45fbd347482c0620ebd6e4dd166e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
